services:
  - redis-server

language: node_js

node_js:
  - "12.22.0"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - $HOME/.npm
    - $HOME/.meteor

notifications:
  email: false

script:
  - meteor create --release 1.11.1 --bare test
  - cd test
  - meteor npm i --save puppeteer@1.18.1 simpl-schema chai bcrypt
  - meteor test-packages --raw-logs --once --driver-package meteortesting:mocha ../
env:
  - METEOR_PACKAGE_DIRS=../
  - TEST_BROWSER_DRIVER=puppeteer
